config/routes.rb
Ticketing::Application.routes.draw do
  
  devise_for :users
  resources :tickets do
    get :complete, on: :member
  end

  root "tickets#index"

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tickets

  def name_display
    if first_name || last_name
      "#{first_name} #{last_name}".strip
    else
      email
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name 
    devise_parameter_sanitizer.for(:sign_up) << :last_name 
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @tickets = Ticket.all
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = current_user.tickets.new ticket_params
    if @ticket.save
      redirect_to tickets_url
    else
      render :new
    end
  end

  def complete
    @ticket = Ticket.find(params[:id])
    if @ticket.user === current_user
      @ticket = current_user.tickets.find(params[:id])
      if @ticket.status == false    
        @ticket.status = true
        @ticket.save
      else
        @ticket.status = false
        @ticket.save
      end    
      redirect_to tickets_path
    else
      redirect_to tickets_path, alert: "Sorry, you can not edit this ticket"
    end
    # respond_to do |format|
    #   if @ticket.save
    #     format.html {redirect_to tickets_url, notice: "Thanks for your Ticket!"}
    #     format.js 
    #   else
    #     redirect_to tickets_url
    #   end
    # end
  end

  private

  def ticket_params
    params.require(:ticket).permit([:title, :body])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ticket_helper.rb
module TicketHelper
end

app/views/layouts/_flash.html.haml
- flash.each do |name, msg|
  .row
    .col-md-10.col-md-offset-1
      .alert{class: "alert-#{ name == :notice ? 'success' : 'danger' }"}
        %a.close{href: '#', data: {dismiss: 'alert'}} &times;
        %div= msg
.clearfix

app/views/layouts/_main_nav.html.haml
%nav.navbar.navbar-default
  .navbar-header
    %a.navbar-brand{href: root_url} Ticket Town
  #name
    %p
      - if user_signed_in? 
        = link_to current_user.name_display, edit_user_registration_path 
        |
        = link_to "Sign Out", destroy_user_session_path, method: :delete 
        
      - else 
        = link_to "Register", new_user_registration_path 
        |
        = link_to "Sign In", new_user_session_path 
     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ticketing</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/main_nav" %>
<%= render "layouts/flash" %>
<div class="container">

  <%= yield %>
</div>
</body>
</html>

app/views/tickets/complete.js.erb
$(this).on('click', function () {
  var Status = $(this).val();
  $.ajax({
    if Status == true {
      Status = false;
      $(this).html("Mark Resolved");
    } else {
      Status = true;
      $(this).text("Resolved");
      }
  });
});

app/views/tickets/index.html.haml
%h3 Ticket Town:
%hr
-@tickets.each do |ticket|
  %section
    = ticket.title
    %br
    = ticket.body        
    %br
    Created by:
    = ticket.user.name_display
    #resolved
      - if ticket.status == false
        = link_to "Mark Resolved?", complete_ticket_path(ticket)
      - else
        = link_to "Resolved", complete_ticket_path(ticket)
%a.btn.btn-default{href: new_ticket_path}New Ticket

app/views/tickets/new.html.haml
%h1 Add a New Ticket
= form_for @ticket do |f|
  .form-group
    = f.label :title, "Title"
    = f.text_field :title, class: "form-control" 
    %br
    = f.label :body, "Enter New Answer" 
    = f.text_area :body, class: "form-control" 
    %br
    = f.submit class: "btn btn-default"